### ISSUE TITLE
RPR 2.0 Beta (2.5.1)  Lighting bug 

### ISSUE THREAD

**Issue by MakramDaou** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#69] opened 2020-08-20 07:57 UTC
Simple Cornell Box lighting test shows an issue when rendering in RPR 2.0 (2.5.1)

Using an emissive

[Cornell_box_emissive.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/5101493/Cornell_box_emissive.zip)

RPR 1 (Full):
![RPR1_emissive](https://user-images.githubusercontent.com/46979415/90732233-19f5d080-e2cb-11ea-9106-a603316b8444.png)

RPR 2:
![RPR2_emissive](https://user-images.githubusercontent.com/46979415/90732280-29751980-e2cb-11ea-9f0a-21ff2728c15e.png)

Using an Area Light

[Cornell_box_area.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/5101497/Cornell_box_area.zip)

RPR1 (Full):
![RPR1_area](https://user-images.githubusercontent.com/46979415/90732302-3265eb00-e2cb-11ea-94ae-5637a77cce12.png)

RPR2:
![RPR2_area](https://user-images.githubusercontent.com/46979415/90732322-398cf900-e2cb-11ea-889a-9d20eb7862e7.png)

Specs:
Windows 10 2004
i7 6700K
32GB
Radeon VII (latest Pro drivers)
Blender 2.8.3

Mak

**Comment by bsavery** [comment] 2020-08-20 14:53
What are you enabling for render devices?  This info is not shared in the scene file.

**Comment by MakramDaou** [comment] 2020-08-20 14:58
Enabling only the GPU (Radeon VII)

Mak

**Comment by bsavery** [comment] 2020-08-25 18:59
Hi @MakramDaou so two issues here.  
1.  I can't reproduce your bug with the area light version.  those are weird artifacts.
2.  It seems something more subtle is going on here.  If you move the light up and down (in Z) you'll see it's an artifact of the back side of the light bouncing. Still investigating here.

**Comment by MakramDaou** [comment] 2020-08-25 19:03
What's also strange (besides the artifacts) is the shadow on the green wall in the RPR 2 renders.

Mak

**Comment by bsavery** [comment] 2020-08-26 02:24
Yep.  Were looking into it

**Comment by MakramDaou** [comment] 2020-09-20 12:18
@bsavery any success tracking down the issue ?

Mak

**Comment by bsavery** [comment] 2020-09-20 19:56
I did actually.  I took a look at the green wall.  It seems you have a normal map node hooked up with no normal map?  If I remove that it gets rid of the weird shadows on the wall.

**Comment by MakramDaou** [comment] 2020-09-20 21:30
@bsavery 
Removing it those indeed fix the shadowing issue! The normal map node is automatically created by Blender when a new Principaled BSDF material is added to a mesh. 
Still having the backside bounce lighting artifact with the emissive light though (area light scene is now working as it should). 

Mak

**Comment by bsavery** [comment] 2020-11-02 19:11
Should be fixed with latest RPR 2

**Closed by bsavery** 2020-11-02 19:11 UTC
