### ISSUE TITLE
Metalness produces unexpected (and unrealistic) results - extended comparison

### ISSUE THREAD

**Issue by DaQuteness** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#67] opened 2020-08-19 15:55 UTC
Windows 10 2004, Threadripper 2990WX, 2x Radeon VII
Tested RPR 2.4 for Blender, RPR 2.9 for Maya, reproducible in every version so far, including C4D's latest

Summing it up as concise and clearly as I possibly can - using Metalness will result in a very bright tangent reflection/halo even when there realistically should not be one. For your convenience, I have tested the same settings (Black base colour, Metalness set to 1.0, Reflection Colour set to black and Reflection Roughness set to 1.0, disabled every other shader layer) on 5 different render engines: RPR, Cycles, LuxCore, Arnold and Pixar RenderMan 23.4, which I assume we can all agree is an industry-leading engine and therefore the best reference. Other testers have provided results for RPR in C4D, as well as comparison images for C4D Standard and Octane Render however none of the latter exhibit this reflection behaviour, only ProRender in C4D does.

Please see image and scene attached for comparison (including shader settings used) and a Blender scene with RPR and Cycles materials set up for you to debug.
![RPR-MetalnessComparison](https://user-images.githubusercontent.com/58505818/90658846-f0da2f00-e23b-11ea-8399-42cb60c1416e.png)
[RPRMetalnessTest.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/5097583/RPRMetalnessTest.zip)

If there is any other information required, please let me know. After discussing with other testers and distilling the information as best as possible, I don't know how I could better explain it other than the Metalness factor, be it with Uber or Principled shader, produces unexpected and unrealistic results.

Hope this helps!

Many thanks,
Valentin

**Comment by MakramDaou** [comment] 2020-08-19 16:25
I can confirm the same behavior:

Cycles:
![Annotation 2020-02-10 192017 (2)](https://user-images.githubusercontent.com/46979415/90662932-4d901680-e249-11ea-90f9-da3982cd4503.jpg)


RPR:
![Annotation 2020-02-10 191836 (2)](https://user-images.githubusercontent.com/46979415/90662951-54b72480-e249-11ea-9d7b-c1232d62f8b2.jpg)

Mak

**Comment by bsavery** [comment] 2020-08-19 17:45
Thanks for posting.  I think this is a bit deeper in renderer than Blender plugin but we'll look.

**Comment by MakramDaou** [comment] 2020-08-19 22:56
This may or may not be related but there has also always been a rather big difference between Cycles (and other renderers) & RPR in terms of diffuse bounce light.

As seen in the shots below there's way less red color bounced back on the panther in RPR compared to Cycles (similar settings were used in both cases):

Cycles:
![Cyclesx](https://user-images.githubusercontent.com/46979415/90697799-81862e80-e27f-11ea-9042-e0183875e5a3.png)


RPR:
![RPR2x](https://user-images.githubusercontent.com/46979415/90697816-89de6980-e27f-11ea-86e2-810efcfa00f7.png)

Mak

**Comment by bsavery** [comment] 2020-11-20 18:28
@MakramDaou and @DaQuteness are you satisfied with changes?

**Comment by MakramDaou** [comment] 2020-11-20 21:43
@bsavery 
Still looks off in 3.0.1

RPR2 (With Metallic cranked to 1):
![RPR2Metal](https://user-images.githubusercontent.com/46979415/99852648-b2794680-2b81-11eb-9150-831233f0b129.jpg)


Cycles (With Metallic cranked to 1):
![CyclesMetal](https://user-images.githubusercontent.com/46979415/99852671-befd9f00-2b81-11eb-8181-9eb1a9a1fe16.jpg)

**Comment by bsavery** [comment] 2020-11-20 23:57
Hmmm.  I think I'll have to make a more simple example.

**Comment by DaQuteness** [comment] 2020-11-21 00:10
I've been swamped with work at the office, on top of moving house, and
haven't had the chance to test but I'll get on it tomorrow morning and post
the findings. That example looks miles better than before though.

**Comment by DaQuteness** [comment] 2020-11-21 09:52
![image](https://user-images.githubusercontent.com/58505818/99874324-f6e6ff80-2bde-11eb-9a14-e90343578048.png)

Metalness is unchanged on newest version. Looks certainly better than before in @MakramDaou 's image but it's still a problem, especially with dark shaders. Please see original post for indication of expected results.

**Comment by MakramDaou** [comment] 2020-11-24 23:14
It appears that metalness is always on/cranked up even when set to 0.

Full:
![RPRFull](https://user-images.githubusercontent.com/46979415/100161959-c212cb00-2eb2-11eb-9ac0-275f4610a835.jpg)

Legacy:
![Legacy](https://user-images.githubusercontent.com/46979415/100161971-c6d77f00-2eb2-11eb-9879-17323931aa25.jpg)

Cycles:
![Cycles_s](https://user-images.githubusercontent.com/46979415/100161977-cc34c980-2eb2-11eb-853b-d138cdf61498.jpg)

Full (Roughness->0):

![Full_metal0](https://user-images.githubusercontent.com/46979415/100162102-13bb5580-2eb3-11eb-805c-c4fb98ef4075.jpg)

**Comment by bsavery** [comment] 2020-11-25 21:33
This seems to be only an issue with the multiplication of color into the metallic brdf.  i.e. with real colors look fine.  Looking into it.

**Comment by MakramDaou** [comment] 2020-11-25 21:45
@bsavery What do you mean by "with real colors" ?

**Comment by bsavery** [comment] 2020-11-25 23:24
Well higher value colors than black ;)

**Comment by MakramDaou** [comment] 2020-11-25 23:29
Seems to happen no matter the color/texture. Really looks like Metalness is  always ON 🤷‍♀️

Full:
![Full_pink](https://user-images.githubusercontent.com/46979415/100291570-6d3c8680-2f7e-11eb-8ab5-0bc50a949553.jpg)

Legacy:
![Legacy_pink](https://user-images.githubusercontent.com/46979415/100291579-73326780-2f7e-11eb-9062-699d56dfe960.jpg)

**Comment by bsavery** [comment] 2020-11-25 23:41
Legacy was incorrect.  I'm not sure I agree with what you're saying.  To be clear, the basic effect of metalness is that it changes the reflection color from white (0 metalness) to whatever color the base color is (1 metalness) mixing between the two.  

So your arrow there pointing to the highlight is expected.  https://blog.selfshadow.com/publications/s2012-shading-course/burley/s2012_pbs_disney_brdf_slides_v2.pdf

**Comment by MakramDaou** [comment] 2020-11-26 00:04
I agree. but this would mean that Cycles got it wrong then:

Cycles Meatlness 0:
![Cycles_pink](https://user-images.githubusercontent.com/46979415/100292874-13d65680-2f82-11eb-9719-a2c453a4ccb6.jpg)

Cycles Metalness 0.5:
![Cycles_pink05](https://user-images.githubusercontent.com/46979415/100292879-189b0a80-2f82-11eb-8d6d-ffeb787751f6.jpg)

Cycles Metlaness 1:
![Cycles_pink1](https://user-images.githubusercontent.com/46979415/100292887-218bdc00-2f82-11eb-957a-d925d06997d9.jpg)


The thing with RPR2 that stands out is that even when the roughness is cranked out to 1 there's still the same "rim lighting" present whether Metalness is set to 0, 1 or in between:

RPR2:
![RPR2_pink](https://user-images.githubusercontent.com/46979415/100293122-f655bc80-2f82-11eb-9abe-76bccf5ee2eb.jpg)

Marmoset Toolbag 4 at same settings (Metalness and Roughness @ 1):
![MT4](https://user-images.githubusercontent.com/46979415/100293143-05d50580-2f83-11eb-990b-2726838fac1d.jpg)

**Comment by MakramDaou** [comment] 2020-12-08 02:34
RPR2:
![rpr2](https://user-images.githubusercontent.com/46979415/101430940-4a0ec100-3906-11eb-8612-7d1885f158d8.png)

Cycles:
![Cycles](https://user-images.githubusercontent.com/46979415/101430953-509d3880-3906-11eb-9659-17528720f62d.png)

🤷‍♀️

**Comment by ARozghon** [comment] 2020-12-08 09:38
![image](https://user-images.githubusercontent.com/68949117/101466476-dd1d1a80-3949-11eb-8b82-feced4533378.png)
fast reflection comparison between Principle and Uber (IOR)

**Comment by MakramDaou** [comment] 2020-12-14 17:36
I don't even think that it's strucly a metalness issue (it's set to 0 in my previews sneakers render).

Cycles (the only one that looks correct):
![Screenshot 2020-12-14 182442](https://user-images.githubusercontent.com/46979415/102114391-6b0d6f80-3e3a-11eb-9422-ab6cd5253dc2.jpg)

RPR2 with UBER Shader with Reflection Use Shader Normal set to Metlaness:
![Screenshot 2020-12-14 182534](https://user-images.githubusercontent.com/46979415/102114621-b6c01900-3e3a-11eb-984b-bd1f4b8a6500.jpg)

RPR2 with UBER Shader with Reflection Use Shader Normal set to IOR:
![Screenshot 2020-12-14 182630](https://user-images.githubusercontent.com/46979415/102114862-030b5900-3e3b-11eb-8cd3-69446b2ae6bd.jpg)

**Comment by bsavery** [comment] 2020-12-14 17:56
Hi guys.  I'm agreeing we have to fix this, but I can't do it directly in the plugin, has to come from the renderer itself, so it's going to take a bit of time.  Please be patient.

**Comment by MakramDaou** [comment] 2020-12-30 16:50
@bsavery Any estimated ETA on a possible fix ?

**Comment by bsavery** [comment] 2021-04-02 14:37
We think this is recently fixed in the RPR Core SDK, will be fixed in an upcoming build.

**Comment by bsavery** [comment] 2021-07-13 14:31
Closing due to fix.  Please reopen if issue observed.

**Closed by bsavery** 2021-07-13 14:31 UTC
