### ISSUE TITLE
Image mapping failed at file

### ISSUE THREAD

**Issue by homeworker** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#106] opened 2020-10-22 12:57 UTC
Hello, I get this error when click on Viewport Shading "rendered" for preview. Is a scene with a globe displaced (earth) and a simple fluid simulation with Flip fluid addon (commercial).

I have an Asus laptop with GeForce GTX 950M and a Intel(R) HD Graphics 530
Blender 2.90.1
Radeon 2.5.1

Other than that I can't render with radeon pro render because after the syncing objects blender freeze and close.

Thanks

[ERROR@RIF]: Image mapping failed at file C:\JN\WS\RadeonProImageProcessor_Build\src\Image.cpp line 600
2020-10-22 14:40:35,509 ERROR rpr.viewport_engine [9212]:  RIF call ImageMap(<pyrprimagefilters.Image object at 0x00000130A1677EC8>, 2, <cdata 'void * *' owning 8 bytes>) returned error code <-21> with error message: '' EXCEPTION: Traceback (most recent call last):
  File "C:\Users\____\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\rprblender\engine\viewport_engine.py", line 399, in _do_sync_render
    self.update_image_filter_inputs()
  File "C:\Users\____\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\rprblender\engine\engine.py", line 386, in update_image_filter_inputs
    self.image_filter.update_input(input_id, data, tile_pos)
  File "C:\Users\____\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\rprblender\engine\image_filter.py", line 78, in update_input
    self.inputs[input_id].set_data(data, pos)
  File "C:\Users\____\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\rprblender\pyrprimagefilters.py", line 227, in set_data
    ImageMap(self, IMAGE_MAP_WRITE, mapped_data)
  File "C:\Users\____\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\rprblender\pyrpr.py", line 78, in wrapped
    raise CoreError(status, f.__name__, argv, module_name)
pyrpr.CoreError: RIF call ImageMap(<pyrprimagefilters.Image object at 0x00000130A1677EC8>, 2, <cdata 'void * *' owning 8 bytes>) returned error code <-21> with error message: ''

**Comment by bsavery** [comment] 2020-10-22 15:31
Can you send the image file that is failling?

**Comment by homeworker** [comment] 2020-10-22 15:50
Of course, is 87mb without the baked flipfluid cache.

**Comment by homeworker** [comment] 2020-10-23 07:04
Thanks, was the hdri
Rename it in small_harbor_01_4k.zip.001 and small_harbor_01_4k.zip.002 and open it with 7zip

[small_harbor_01_4k002.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/5427811/small_harbor_01_4k002.zip)
[small_harbor_01_4k001.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/5427810/small_harbor_01_4k001.zip)

**Comment by homeworker** [comment] 2020-10-23 07:26
Texture
![Albedo](https://user-images.githubusercontent.com/4161571/96967530-f1c75f80-150f-11eb-9a76-d0d86f47ba94.jpg)
![Bump](https://user-images.githubusercontent.com/4161571/96967541-f7bd4080-150f-11eb-9b15-7ec4993c7305.jpg)
![Clouds](https://user-images.githubusercontent.com/4161571/96968799-cba2bf00-1511-11eb-815c-d02cbad3a45a.png)
![night_lights_modified](https://user-images.githubusercontent.com/4161571/96968823-d5c4bd80-1511-11eb-8a84-6a17b740370b.png)
![Ocean_Mask](https://user-images.githubusercontent.com/4161571/96968834-d9584480-1511-11eb-8ef6-ad54355ed96d.png)

**Comment by ardraeiss** [comment] 2020-11-02 19:34
Hello. I'm unable to reproduce issue from that info.
Could you share what Denoiser settings are you using and what is the render size?

**Comment by bsavery** [comment] 2020-11-20 18:40
Closing until @homeworker responds.

**Comment by homeworker** [comment] 2020-11-24 17:32
I can share a wetransfer with the .blend if you can share an e-mail.

**Comment by bsavery** [comment] 2020-11-24 17:41
please send to brian dot savery at amd dot com

**Comment by homeworker** [comment] 2020-11-25 08:18
Sending now.
Images are packed in .blend
Thanks

**Comment by ardraeiss** [comment] 2020-12-14 09:06
Thank you, this scene crashes for me in more than one way.

**Comment by bsavery** [comment] 2021-04-02 14:41
@ardraeiss will re-verify

**Comment by bnagirniak** [comment] 2021-06-30 07:49
Due to error log in the description this bug relates to Image filters (RIF), some internal error happen in it. RIF was updated several times from the time when this issue was created. Please verify it with latest build.
Closing until respond.

**Closed by bnagirniak** 2021-06-30 07:49 UTC
