### ISSUE TITLE
I cant enable add-on in preferences - WinError 1920

### ISSUE THREAD

**Issue by larinius** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#206] opened 2021-02-14 09:28 UTC
I cant enable add-on in preferences. Always have "Winerror 1920" - path not found. 
My Blender in the default windows 10 location.

Blender version: 2.91.2, branch: master, commit date: 2021-01-19 16:15, hash: 5be9ef417703, type: Release
build date: 2021-01-19, 16:25:50
platform: Windows

![Blender Preferences 14 02 2021 11_22_34](https://user-images.githubusercontent.com/5310985/107872956-0fea0e80-6eb7-11eb-90fb-39f2305a508f.png)

**Comment by bnagirniak** [comment] 2021-02-20 10:56
What RPR plugin version do you use? Similar issue was fixed several months ago.

**Comment by bsavery** [comment] 2021-04-02 15:10
Closing as duplicate of #111

**Closed by bsavery** 2021-04-02 15:10 UTC
