### ISSUE TITLE
Enabling Error

### ISSUE THREAD

**Issue by ApplicationCoding** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#475] opened 2022-03-28 02:23 UTC
## Issue
When I enable Radeon ProRender, I keep getting this error:
![Screenshot 2022-03-28 084758](https://user-images.githubusercontent.com/76902392/160314633-5a88beab-5215-4056-b756-a76e2acedd9f.png)

## Steps to Reproduce
Blender (.blend) file: https://mega.nz/file/kzRRCCDZ#ugbffVB9VSVAfOC5dpVzrSp-7vJMknGknu_YO1VKqJE
1. Download Radeon ProRender for Blender from AMD website/ GitHub.
2. Install addon in Blender
3. Enable the addon

## System Setup (Environment)
OS: Windows 10 Pro 21H2 (OS Build 19044.1620)
GPU: Intel(R) HD Graphics 4600, 
CPU: Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz
Driver Version: 20.19.15.5171
Blender version: 3.1.0
Using GPU Rendering

## Detailed Description
The image attached above is the error I keep getting when I enable Radeon ProRender. Already tried restarting Blender and re-installing the addon but still won't fix it.

**Comment by bsavery** [comment] 2022-03-28 03:53
Duplicate of https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/issues/461 please subscribe to that issue.  A fix is in progress, but I would point out this is the blender foundation's bug because they switched Python versions just before releasing 3.1

**Closed by bsavery** 2022-03-28 03:53 UTC

**Comment by ApplicationCoding** [comment] 2022-03-28 03:56
Ohhh. Also, just subscribed to #461 too. Thanks!
