### ISSUE TITLE
From Medium to high quality

### ISSUE THREAD

**Issue by insertcoindottv** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#29] opened 2020-06-24 21:58 UTC
Hi all, we have some trouble between the RPR Medium settings and High Setting. Some polygons disappears or look badly. This occur only with AMD cards (RadeonProDuo 32Gb Polaris + 5700xt), While with 2 titan Nvidia there is no problem at all...

[system-info.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/4828036/system-info.txt)

![image](https://user-images.githubusercontent.com/36404492/85631466-df2e3e00-b675-11ea-92e5-069558d6fd48.png)
![image](https://user-images.githubusercontent.com/36404492/85631500-ef461d80-b675-11ea-95d3-6dcb51cde955.png)

In System Info generated from blender, you can see details of harware.

We also notice that working in a project with a lot of objects (900+), and trying to show them as "medium" quality, when Rpr calculate around 450pz it crash. No way. While in full global illum. no preblem.

Thanks.

**Comment by bsavery** [comment] 2021-04-02 14:36
Duplicate of #13

**Closed by bsavery** 2021-04-02 14:36 UTC
