### ISSUE TITLE
Blender is unusable for me.  Pixelated graphics

### ISSUE THREAD

**Issue by negaunee042** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#479] opened 2022-04-05 21:31 UTC
I am using Radeon Pro Render 3.3 and blender 3.0 and (have also tried installing all other compatible versions with same issue)  GPU is a radeon 5700xt, CPU is ryzen 9 3900x.  I am getting really bad renders and previews even in blender.  This is the most basic scene, 1 cube and a material from the rpr library, and I cannot render that even.  Texture resolution; 4096 Quality; final.    Cycles is the same.  I was having better renders before installing pro render using the CPU alone altho it took forever for renders.

![untitled](https://user-images.githubusercontent.com/97860719/161852754-b374a6a2-0cb5-4cf2-999b-998c95f33b68.png)

**Comment by bsavery** [comment] 2022-04-05 21:57
Hi.  I don't quite understand this.  You say you can't render the picture above?  How did you make that one.  Also you mention it being pixelated.  It's a bit hard to tell in your render if it's just noise or the texture.  When you opened an "issue" it says to attach a scene.  Please do that.  Or if the render is failing please attach an error log:

"Every issue should include 3 things:
1.  System setup (GPU, CPU, OS version, Blender version)
2.  **Most ideally** a .blend scene to reproduce this simply.  **SCREENSHOTS OR RENDERS ARE NOT A SCENE FILE**
3.  What the expected behavior or effect is.  If possible include the error message.  

You can get more information on the error message by opening Window -> Show System Console from blender and copying that text here.  On MacOS launch Blender from the Terminal.




## Issue


## Steps to Reproduce



## System Setup (Environment)





## Detailed Description
"

**Comment by negaunee042** [comment] 2022-04-07 21:13
> Hi. I don't quite understand this. You say you can't render the picture above? How did you make that one. Also you mention it being pixelated. It's a bit hard to tell in your render if it's just noise or the texture. When you opened an "issue" it says to attach a scene. Please do that. Or if the render is failing please attach an error log:
>

I just meant everything I try to render is real low quality and pixelated (using both standard colors and provided radeon materials).  I am also getting a grey viewport mode half of the time.  Settings do not matter however, I've tried every setting and every message board.  There is lack of depth and quality to any rendering, which makes doing any kind of artwork pointless.  I've been having to use my 1gb Nvidia laptop in the meantime.  Today I tried Blender 3.1 with the 3.26prorender and had the same results.   The system I'm having issues with has a Ryzen 3900x 24 thread cpu, x570 motherboard, 34gb of ram, and radeon 5700x gpu.  
![image](https://user-images.githubusercontent.com/97860719/162312417-451cbedb-f0b2-4e13-8655-c0d75d6179ca.png)

**Comment by bsavery** [comment] 2022-04-08 15:21
Hi there.  We've asked twice for a scene. Please attach one showing the issue so we can look closer.  Otherwise I'm going to close this issue.

**Comment by ARozghon** [comment] 2022-04-08 15:54
hm, an interesting issue with refraction material. need to investigate it with IBL and without IBL and with different types of lights, because with the default Blender scene I got the same result with 6800 XT

**Comment by negaunee042** [comment] 2022-04-14 03:01
> Hi there. We've asked twice for a scene. Please attach one showing the issue so we can look closer. Otherwise I'm going to close this issue.

I'm sorry I'm an artist not a developer.  It's happening to every single 3d object I make.  What do you want by a "scene"?   That's why I showed the 1 cube and 1 material.  What else do I need to add? It's happening to every single object.  This was the example I was trying to give.  This is 1 cube of default size.  I selected the 
"glass solid green-blue" from the Radeon ProRender Material library.  There is definitely issues with shading that are affecting everything I try to render.  I've been having to use my CPU on cycles which is quite a bit better, but still nowhere near perfect.   If you need me to elaborate on "my scene" please tell me what exactly you need.  I'm an artist who has spent days on end trying to figure my issues out with this software and do not come from a developer background.   I have been getting this error trying to render on medium or high.
![image](https://user-images.githubusercontent.com/97860719/163304849-c2c578a2-7893-4ec9-a48e-9737d9796081.png)
 If I try to render on low quality, the cube is black.  If I render on "final" I get this highly pixelated render;
![bluegreenglashonfinal](https://user-images.githubusercontent.com/97860719/163305106-7b443cbe-7135-4f4a-8b16-a6163014e1a8.png)

**Comment by negaunee042** [comment] 2022-04-14 03:30
This helps show the problem also.  I've tried all the different blender and prorender versions.  I even tried the latest that goes along with blender 3.12.  Pixelation + noise with having the highest quality and denoiser selected.  
![image](https://user-images.githubusercontent.com/97860719/163308207-20fb2bfe-7548-4a81-9a4f-ec7f78b5de10.png)

**Comment by bsavery** [comment] 2022-06-10 14:30
I'm closing this issue until someone can attach a scene as I've asked.

**Closed by bsavery** 2022-06-10 14:30 UTC

**Comment by negaunee042** [comment] 2022-06-11 19:02
> I'm closing this issue until someone can attach a scene as I've asked.

That's fine.  I bought a Nvidia graphics card so my amd is idle for now.
