### ISSUE TITLE
RPR 3.1 crash on render start 6700xt

### ISSUE THREAD

**Issue by DesperateZero** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#259] opened 2021-04-11 01:55 UTC
![image](https://user-images.githubusercontent.com/15711880/114289598-dd6e2380-9aab-11eb-962e-c1daf7301ecd.png)

[MSG  @RIF]: Loading model: C:\Users\_DespAir\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\rprblender\data\models/esrgan-05x3x32-278391.pb
I N F O :   M e m o r y :   a l l o c a t e d :   3 4 5 5 5 1 6 6 7 2 ,   b e s t :   2 4 2 5 8 8 0 5 7 6 ,   w o r s t :   6 7 6 1 2 4 4 2 6 2 4
 [ERROR@RIF]: Generator/SubpixelConv2d/DepthToSpace:DepthToSpace: IDMLDevice::CompileOperator returned 887a0005: GPU ?瀷蛳俓( GetDeviceRemovedReason 錸汎攧 at file C:\JN\WS\RadeonProImageProcessor_Build\src\AIFilters.cpp line 5872021-04-11 09:36:45,548 ERROR rpr.viewport_engine [18608]:  RIF call ContextExecuteCommandQueue(<pyrprimagefilters.Context object at 0x0000022A159A6648>, <pyrprimagefilters.CommandQueue object at 0x0000022A159FF148>, <cdata 'void *' NULL>, <cdata 'void *' NULL>, <cdata 'void *' NULL>) returned error code <-21> with error message: '' EXCEPTION: Traceback (most recent call last):
  File "C:\Users\_DespAir\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\rprblender\engine\viewport_engine.py", line 449, in _do_sync_render
    self._do_render()
  File "C:\Users\_DespAir\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\rprblender\engine\viewport_engine_2.py", line 242, in _do_render
    self.upscale_filter.run()
  File "C:\Users\_DespAir\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\rprblender\engine\image_filter.py", line 109, in run
    self.command_queue.execute()
  File "C:\Users\_DespAir\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\rprblender\pyrprimagefilters.py", line 366, in execute
    ContextExecuteCommandQueue(self.context, self, ffi.NULL, ffi.NULL, ffi.NULL)
  File "C:\Users\_DespAir\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\rprblender\pyrpr.py", line 78, in wrapped
    raise CoreError(status, f.__name__, argv, module_name)
pyrpr.CoreError: RIF call ContextExecuteCommandQueue(<pyrprimagefilters.Context object at 0x0000022A159A6648>, <pyrprimagefilters.CommandQueue object at 0x0000022A159FF148>, <cdata 'void *' NULL>, <cdata 'void *' NULL>, <cdata 'void *' NULL>) returned error code <-21> with error message: ''

r5 5600x
64g ram
rx6700xt
blender2.83

**Comment by bsavery** [comment] 2021-04-11 03:30
Duplicate of this issue:  https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/issues/251

**Closed by bsavery** 2021-04-11 03:30 UTC
